package constants

const (
	CONFIG_BOOTSTRAP_SERVERS  = "bootstrap.servers"
	CONFIG_GROUP_ID           = "group.id"
	CONFIG_AUTO_OFFSET_RESET  = "auto.offset.reset"
	CONFIG_ENABLE_AUTO_COMMIT = "enable.auto.commit"
	CONFIG_SECURITY_PROTOCOL  = "security.protocol"
	CONFIG_SASL_MECHANISM     = "sasl.mechanism"
	CONFIG_SASL_USERNAME      = "sasl.username"
	CONFIG_SASL_PASSWORD      = "sasl.password"

	CONFLUENT_TOPIC_API_KEY    = "CONFLUENT_TOPIC_API_KEY"
	CONFLUENT_TOPIC_API_SECRET = "CONFLUENT_TOPIC_API_SECRET"
	SCHEMA_REGISTRY_USERNAME   = "SCHEMA_REGISTRY_USERNAME"
	SCHEMA_REGISTRY_PASSWORD   = "SCHEMA_REGISTRY_PASSWORD"
	KAFKA_BOOTSTRAP_SERVERS    = "KAFKA_BOOTSTRAP_SERVERS"
	SCHEMA_REGISTRY_URL        = "SCHEMA_REGISTRY_URL"

	SECURITY_PROTOCOL_SASL_SSL = "SASL_SSL"
	SECURITY_MECHANISM         = "PLAIN"
	TRACE_ID                   = "Trace_ID"
	SPAN_ID                    = "Span_ID"
	DD_SERVICE                 = "DD_SERVICE"
)
